apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: nectar
  name: nectar-dev

---

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: nectar-dev
subjects:
  - kind: User
    name: system:serviceaccount:nectar:nectar-dev
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
