---
apiVersion: v1
kind: Pod

metadata:
  name: fast-kapi
  namespace: nectar
  labels:
    app: fast-kapi

spec:
  serviceAccountName: nectar
  containers:
    - name: main
      image: xaviermillot/kapi-test:latest
      imagePullPolicy: 'Always'
      ports:
        - containerPort: 5000
